const {test,expect,chromium,webkit}=require('@playwright/test');
const fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..');let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+'/')||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.svg')?'image/svg+xml':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;});
test.afterAll(async()=>server&&await new Promise(r=>server.close(r)));
for(const mobile of [false,true])test('expedition details and GPX '+(mobile?'mobile':'desktop'),async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/comments?*',r=>r.fulfill({json:{comments:[]}}));await page.goto(base+'/index.html');await page.evaluate(()=>{hideGate();openCourseComments('course_k1790337080336',{id:1790337080336,owner:'admin',name:'엑스페디션#11 북한강',km:25.13,coords:[[38.1,127.7],[38.0,127.6]]},'k1790337080336');});
 await expect(page.locator('#pmTitle')).toContainText('엑스페디션 #11 · 북한강 · 구만오월길');await expect(page.locator('.expedition-nicknames')).toHaveText('등록된 참가자 정보가 없습니다');await expect(page.locator('#pmLinks')).toContainText('25.13km');await expect(page.locator('#pmSend')).toBeVisible();await expect(page.locator('.expedition-sticker img')).toBeVisible();expect(await page.locator('.expedition-sticker img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'↓ GPX 다운로드'}).click();const d=await download;expect(d.suggestedFilename()).toBe('엑스페디션 #11 · 북한강 · 구만오월길.gpx');const xml=fs.readFileSync(await d.path(),'utf8');const parsed=await page.evaluate(xml=>{const doc=new DOMParser().parseFromString(xml,'application/xml');return {error:!!doc.querySelector('parsererror'),version:doc.documentElement.getAttribute('version'),ns:doc.documentElement.namespaceURI,points:[...doc.getElementsByTagName('trkpt')].map(x=>[+x.getAttribute('lat'),+x.getAttribute('lon')]),invented:doc.querySelectorAll('time,ele').length};},xml);expect(parsed).toEqual({error:false,version:'1.1',ns:'http://www.topografix.com/GPX/1/1',points:[[38.1,127.7],[38,127.6]],invented:0});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'/tmp/expedition-'+(mobile?'mobile':'desktop')+'.png',fullPage:true});expect(errors).toEqual([]);await browser.close();
});
test('all saved coordinates, XML escaping, invalid paths and private courses',async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),p=await b.newPage();await p.goto(base+'/index.html');const result=await p.evaluate(()=>{
 const samples=COURSES.features.map(f=>({name:f.properties.name,coords:f.geometry.coordinates.map(c=>[c[1],c[0]])}));const results=samples.map(c=>{const d=new DOMParser().parseFromString(courseGpx(c),'application/xml'),points=[...d.getElementsByTagName('trkpt')];return points.length===c.coords.length&&+points[0].getAttribute('lat')===c.coords[0][0]&&+points.at(-1).getAttribute('lon')===c.coords.at(-1)[1];});let rejected=0;for(const coords of [[],[[1,2]],[[NaN,2],[3,4]],[[91,2],[3,4]],[[null,2],[3,4]]])try{courseGpx({coords});}catch(e){rejected++;}const name='한글 & <코스> "이름"';const parsed=new DOMParser().parseFromString(courseGpx({name,coords:[[1,2],[3,4]]}),'application/xml');const privateCourse={id:1,owner:'user',name:'엑스페디션#1 개인 코스',coords:[[1,2],[3,4]]};return {results,rejected,escaped:parsed.querySelector('name').textContent===name,privateName:normalizeExpedition(privateCourse,'k1').name,privateDetail:expeditionDetail(privateCourse,'k1')};});expect(result.results.every(Boolean)).toBe(true);expect(result.rejected).toBe(5);expect(result.escaped).toBe(true);expect(result.privateName).toBe('엑스페디션#1 개인 코스');expect(result.privateDetail).toBe('');await b.close();});

test('Safari WebKit mobile GPX download',async()=>{const b=await webkit.launch({headless:true}),p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await p.goto(base+'/index.html');await p.evaluate(()=>{hideGate();openCourseComments('course_k1',{id:1,owner:'user',name:'한글 & 코스',coords:[[37.1,127.2],[37.2,127.3]]},'k1');});const pending=p.waitForEvent('download');await p.getByRole('button',{name:'↓ GPX 다운로드'}).click();const d=await pending;expect(d.suggestedFilename().normalize('NFC')).toBe('한글 & 코스.gpx');expect(fs.readFileSync(await d.path(),'utf8')).toContain('lat="37.1" lon="127.2"');await b.close();});

test('all sticker display masks',async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),p=await b.newPage({viewport:{width:1100,height:1200}});await p.goto(base+'/index.html');await p.evaluate(()=>{document.body.innerHTML='<main style="display:grid;grid-template-columns:repeat(4,1fr);gap:20px;padding:20px;background:#f1f3f6">'+Array.from({length:11},(_,i)=>'<div><h3>'+(i+1)+'회</h3><img class="expedition-art-'+(i+1)+'" style="width:240px;height:270px;object-fit:contain" src="assets/expedition/expedition_'+String(i+1).padStart(2,'0')+([2,3,4,5,9].includes(i+1)?'.jpg':'.png')+'"></div>').join('')+'</main>';});await p.locator('img').evaluateAll(async imgs=>await Promise.all(imgs.map(i=>i.decode())));await p.screenshot({path:'/tmp/expedition-all-stickers.png',fullPage:true});await b.close();});

test('participant fixture uses total attendance ranking and nickname-only display',async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),p=await b.newPage({viewport:{width:390,height:844}});await p.route('**/comments?*',r=>r.fulfill({json:{comments:[]}}));await p.goto(base+'/index.html');await p.evaluate(()=>{const rows=[['one','나래',1],['one','나래',1],['two','가람',1],['two','가람',2],['three','다람',1],['three','다람',2],['three','다람',3],['four','나래',1],['five','닉< & 이름',1]].map(([participantId,nickname,expedition])=>({participantId,nickname,expedition}));EXPEDITION_PARTICIPANTS.splice(0,EXPEDITION_PARTICIPANTS.length,...rows);hideGate();openCourseComments('course_c1',{static:true,id:1,name:'엑스페디션#1'},'1');});expect(await p.locator('.expedition-nickname').allTextContents()).toEqual(['다람','가람','나래','나래','닉< & 이름']);expect(await p.locator('.expedition-nicknames').textContent()).not.toMatch(/회|명/);expect(await p.locator('.expedition-nicknames').innerHTML()).toContain('&lt; &amp;');await b.close();});

test('verified first expedition roster sorts all 14 nicknames without merging people',async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});for(const mobile of [false,true]){const p=await b.newPage({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/comments?*',r=>r.fulfill({json:{comments:[]}}));await p.goto(base+'/index.html');await p.evaluate(()=>{hideGate();courseCmt('c','1');});await expect(p.locator('.expedition-nickname')).toHaveCount(14);expect(await p.locator('.expedition-nickname').allTextContents()).toEqual(['로쟌','묵향','번버리','예건','요트맨','욘니','용부장','잠실벗','쪼리','쭈리','초코파티','카누맨','카누맨2','토끼사냥꾼']);expect(await p.locator('.expedition-nicknames').textContent()).not.toMatch(/회|명/);expect(await p.locator('.expedition-nicknames').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await p.locator('#pmodal .pmodal').evaluate(async e=>await Promise.all(e.getAnimations().map(a=>a.finished)));await p.screenshot({path:'/tmp/expedition-first-roster-'+(mobile?'mobile':'desktop')+'.png',fullPage:true});expect(errors).toEqual([]);await p.close();}await b.close();});

test('static course actions work before override fetch completes',async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),p=await b.newPage();let release;const ready=new Promise(r=>release=r);await p.route('**/course?over=1*',async r=>{await ready;await r.fulfill({json:{}});});await p.goto(base+'/index.html');await p.evaluate(()=>{hideGate();courseCmt('c','1');});await expect(p.getByRole('button',{name:'↓ GPX 다운로드'})).toBeVisible();expect(await p.evaluate(()=>_courseInfoCourse.coords.length)).toBeGreaterThan(1);expect(await p.locator('.expedition-nickname').count()).toBe(14);release();await b.close();});
